### ISSUE TITLE
Queue empty error

### ISSUE THREAD

**Issue by giadefa** [unixpickle/obs-tower2#1]
I am trying to run run_ppo.py but I get this error:

Traceback (most recent call last):
  File "run_ppo.py", line 40, in <module>
    main()
  File "run_ppo.py", line 29, in main
    env = BatchedStateEnv(create_batched_env(NUM_ENVS))
  File "/home/gianni/Challenge/unixpickle/obs-tower2/obs_tower2/util.py", line 47, in create_batched_env
    env_fns)
  File "/home/gianni/Challenge/unixpickle/obs-tower2/obs_tower2/batched_env.py", line 63, in __init__
    self._queue_get(q)
  File "/home/gianni/Challenge/unixpickle/obs-tower2/obs_tower2/batched_env.py", line 143, in _queue_get
    value, exc = queue.get(timeout=20)
  File "/home/gianni/miniconda3/envs/obstacle/lib/python3.6/multiprocessing/queues.py", line 105, in get
    raise Empty
queue.Empty

The obstacle environments seem to start.

Any idea?

**Comment by nmichlo** [comment]
How may I ask did you resolve this?
EDIT: nevermind may have skipped a step setting things up, not sure.

**Comment by giadefa** [comment]
No, I was just interested in the code, but not to run it really.
